import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

import Modal from "../components/Modal";

export default function Home() {
  const [open, setOpen] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Booking Offer For</h1>
        <p className={styles.description}>
          <button
            className={styles.calculate_btn}
            onClick={() => setOpen(!open)}
          >
            Caluclate Price
          </button>
        </p>
        <Modal open={open} setOpen={setOpen} />
      </main>
    </div>
  );
}
